config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/cubes')
  resources :cubes, only: [:index, :new, :create ] do
    member do
      get :send_batch_operations
      post :batch_operations
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/matrix.rb
# == Schema Information
#
# Table name: matrices
#
#  id         :integer          not null, primary key
#  size       :integer          not null
#  data       :binary           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string
#

class Matrix < ApplicationRecord

  validates :name, presence: true
  validates :size, presence: true

  before_save :serialize_tree

  def update_position(x, y, z, val)
    curr_val = sum_range(x, y, z, x, y, z)
    delta = val - curr_val
    i = x
    while i <= self.size
      tree[i] = Hash.new(Hash.new(0)) unless tree.has_key?(i)
      j = y
      while j <= self.size
        tree[i][j] = Hash.new(0) unless tree[i].has_key?(j)
        k = z
        while k <= self.size
          tree[i][j][k] = 0 unless tree[i][j].has_key?(k)
          tree[i][j][k] += delta
          k += (k & -k)
        end
        j += (j & -j)
      end
      i += (i & -i)
    end
  end

  def read_position(x, y, z)
    sum = 0;
    i = x
    while i > 0
      j = y
      while j > 0
        k = z
        while k > 0
          sum += tree[i][j][k]
          k -= (k & -k)
        end
        j -= (j & -j)
      end
      i -= (i & -i)
    end
    sum
  end

  def sum_range(x0, y0, z0, x, y, z)
    value1 = read_position(x, y, z) - read_position(x0 - 1, y, z) -
              read_position(x, y0 - 1, z) + read_position(x0 - 1, y0 - 1, z)
    value2 = read_position(x, y, z0 - 1) - read_position(x0-1, y, z0-1) -
              read_position(x, y0-1, z0-1)  + read_position(x0 - 1, y0 - 1, z0 - 1)
    value1 - value2
  end


  private

    def tree
      @tree ||= if self.data.nil?
        Hash.new(Hash.new(Hash.new(0)))
      else
        Marshal::load(self.data)
      end
    end

    def serialize_tree
      self.data = Marshal::dump(tree)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cubes_controller.rb
class CubesController < ApplicationController

  def index
    @cubes = Matrix.all
  end

  def new
    @cube = Matrix.new
  end

  def create
    @cube = Matrix.new(cube_params)
    if @cube.save
      redirect_to cubes_path
    else
      render :new
    end
  end

  def send_batch_operations
    @cube = Matrix.find(params[:id])
  end

  def batch_operations
    @cube = Matrix.find(params[:id])
    @results = ExecOperationsBatch.call(@cube, params[:batch_operations])
  end

  private

    def cube_params
      params.require(:cube).permit(:size, :name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cubes/batch_operations.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <%= link_to cubes_path do %>
        <span class="glyphicon glyphicon-chevron-left"></span>
        Back to Cubes list
      <% end %>
      <h1>Batch result</h1>
      <ul>
        <% @results.reject(&:blank?).each do |r| %>
          <li><%= r %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/cubes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <h1>Cubes</h1>
      <%= link_to new_cube_path, class: 'btn btn-info' do %>
        <span class="glyphicon glyphicon-plus"></span>
        New cube
      <% end %>
      <div class="table">
        <table class="table">
          <thead>
            <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Size</th>
            </tr>
          </thead>
          <tbody>
            <% @cubes.each do |c| %>
              <tr>
                <td><%= c.id %></td>
                <td><%= c.name %></td>
                <td><%= c.size %></td>
                <td>
                  <%= link_to 'Send Operations', send_batch_operations_cube_path(c) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/cubes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <%= link_to cubes_path do %>
        <span class="glyphicon glyphicon-chevron-left"></span>
        Back to Cubes list
      <% end %>
      <h1>Create a Cube</h1>
      <%= simple_form_for @cube, as: :cube, url: cubes_path do |f| %>
        <%= f.input :name %>
        <%= f.input :size %>
        <%= f.button :submit, value: 'Create Cube' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cubes/send_batch_operations.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <%= link_to cubes_path do %>
        <span class="glyphicon glyphicon-chevron-left"></span>
        Back to Cubes list
      <% end %>
      <h1>Send commands</h1>
      <%= form_tag batch_operations_cube_path(@cube.id) do %>
        <div class="form-group">
          <%= text_area_tag :batch_operations, nil, rows: 15, class: 'form-control' %>
        </div>
        <%= submit_tag :send, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cube</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>